# Gauss-eliminasjon

**TMA4400 Matematikk 1: Kalkulus og lineær algebra**

Dato: **25. august 2025**

## Standard Gauss-eliminasjon

La $A$ være ei $m\times n$-matrise, $\mathbf{x}$ en vektor i $\mathbb{R}^n$ og $\mathbf{b}$ en vektor i $\mathbb{R}^m$. Vi skal løse ligningssystemet $$A\mathbf{x}=\mathbf{b}$$ ved hjelp av Gauss-eliminasjon. 

Vi går ut i fra at pivot-elementene er forskjellig fra null.

In [22]:
import numpy as np

# Gauss-eliminasjon (antar at pivotelementene er forskjellig fra null i alle rader!)
def GE(B):
    A = np.copy(B) # vi lager en kopi av den gitte matrisa B, for å unngå å endre denne
    m,n = np.shape(B) # m=rader, n=kolonner; det er mulig å oppgi den utvidede matrisa, eller tom matrise
    for k in range(0,m-1):
        for j in range(k+1,m):
            l = A[j,k]/A[k,k]
            for p in range(k,n):
                A[j,p] -= l*A[k,p]
    return A

### Eksempel

La oss bruke standard Gauss-eliminasjon på følgende utvidede matrise:
$$(A|b) = \left[\begin{array}{ccc|c} 1 & 4 & 1 & 1 \\ 2 & -1 & 2 & 1 \\ 1 & 3 & 2 & 1 \end{array}\right].$$

In [17]:
A0 = np.array([[1.0,4,1,1],[2,-1,-2,1],[1,3,2,1]])
A1 = GE(A0)
print('\nVi begynner med \n{0}\nog bruker Gauss-eliminering som gitt over: \n{1}'.format(np.matrix(A0),np.matrix(A1)))


Vi begynner med 
[[ 1.  4.  1.  1.]
 [ 2. -1. -2.  1.]
 [ 1.  3.  2.  1.]]
og bruker Gauss-eliminering som gitt over: 
[[ 1.          4.          1.          1.        ]
 [ 0.         -9.         -4.         -1.        ]
 [ 0.          0.          1.44444444  0.11111111]]


### Numerisk ustabilitet

La oss bruke standard Gauss-eliminasjon på følgende utvidede matrise:
$$(A|b) = \left[\begin{array}{cc|c} 10^{-6} & 1 & 1 \\ 1 & 1 & 2  \end{array}\right].$$

In [21]:
B0 = np.array([[1e-6,1,1],[1,1,2]])
B1 = GE(B0)
print('\nVi begynner med \n{0}\nog bruker Gauss-eliminasjon som gitt over: \n{1}'.format(np.matrix(B0),np.matrix(B1)))


Vi begynner med 
[[1.e-06 1.e+00 1.e+00]
 [1.e+00 1.e+00 2.e+00]]
og bruker Gauss-eliminasjon som gitt over: 
[[ 1.00000e-06  1.00000e+00  1.00000e+00]
 [ 0.00000e+00 -9.99999e+05 -9.99998e+05]]


Ved å regne ut for hånd får man
$$(A|b) = \left[\begin{array}{cc|c} 1 & 1 & 2 \\ 0 & 0.999999 & 0.999998  \end{array}\right].$$
Her trenger vi altså en forbedret algoritme for å fange opp tilfellet hvor pivotelementet er lite, men likevel ulikt 0.

## Gauss-eliminasjon med delvis pivotering

En standard måte er såkalt delvis pivotering. Gauss-eliminasjon med delvis pivotering sørger for at pivotelementet har den største absoluttverdien i den aktuelle kolonnen. I tilfellet vi så på, altså 
$$(A|b) = \left[\begin{array}{cc|c} 10^{-6} & 1 & 1 \\ 1 & 1 & 2  \end{array}\right],$$
vil algoritmen begynne med å bytte om på rad 1 og 2 slik at vi ender opp med
$$(A|b) = \left[\begin{array}{cc|c} 1 & 1 & 2 \\ 10^{-6} & 1 & 1  \end{array}\right].$$
Ved å gange første rad med $-10^{-6}$ og legge denne raden til andre rad får vi den riktige matrisa:
$$(A|b) = \left[\begin{array}{cc|c} 1 & 1 & 2 \\ 0 & 1-10^{-6} & 1-2\cdot10^{-6}  \end{array}\right]=\left[\begin{array}{cc|c} 1 & 1 & 2 \\ 0 & 0.999999 & 0.999998  \end{array}\right].$$

In [18]:
# Gauss-eliminasjon med delvis pivotering
def GEPP(B):
    A = np.copy(B) # vi lager en kopi av den gitte matrisa B, for å unngå å endre denne
    m,n = np.shape(A) # m=rader, n=kolonner; det er mulig å oppgi den utvidede matrisa, eller tom matrise
    for k in range(0,m-1):
        a = np.abs(A[k,k])
        pk = k
        for j in range(k+1,m):
            if a < np.abs(A[j,k]):
                a = np.abs(A[j,k])
                pk = j
        if pk != k:
            for p in range(k,n):
                r = A[k,p]
                A[k,p] = A[pk,p]
                A[pk,p] = r
        for j in range(k+1,m):
            l = A[j,k]/A[k,k]
            for p in range(k,n):
                A[j,p] -= l*A[k,p]
    return A


### Eksempel

La oss bruke Gauss-eliminasjon med delvis pivotering på følgende utvidede matrise:
$$(A|b) = \left[\begin{array}{cc|c} 10^{-6} & 1 & 1 \\ 1 & 1 & 2  \end{array}\right].$$

In [24]:
B0 = np.array([[1e-6,1,1],[1,1,2]])
B1 = GEPP(B0)
print('\nVi begynner med \n{0}\nog bruker Gauss-eliminasjon med delvis pivotering som gitt over: \n{1}'.format(np.matrix(B0),np.matrix(B1)))


Vi begynner med 
[[1.e-06 1.e+00 1.e+00]
 [1.e+00 1.e+00 2.e+00]]
og bruker Gauss-eliminasjon med delvis pivotering som gitt over: 
[[1.       1.       2.      ]
 [0.       0.999999 0.999998]]
